# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lustiges Krisenblog
email: gestos@gestos.de
description: > # this means to ignore newlines until "baseurl:"
  Spielplatz zum Design (und Jekyll) ausprobieren
  eventuell auch mal Content zu publizieren
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.gestos.de" # the base hostname & protocol for your site
github_username:  gestos

# Build settings
markdown: kramdown
